/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  r01an1918_rx64m                        */
/*      FILE         :  stacksct.h                             */
/*      DESCRIPTION  :  Setting of Stack area                  */
/*      CPU SERIES   :  RX600                                  */
/*      CPU TYPE     :  RX64M                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/
#pragma stacksize su=0x10000
#pragma stacksize si=0x800
