
#include "luaHelper.h"
#include "../lua.h"
#include "../lauxlib.h"
#include "../lualib.h"

#include <string.h>

/*
** Check whether 'status' is not OK and, if so, prints the error
** message on the top of the stack. It assumes that the error object
** is a string, as it was either generated by Lua or by 'msghandler'.
*/
static int report (lua_State *L, int status) {
  if (status != LUA_OK) {
    const char *msg = lua_tostring(L, -1);
    lua_writestring(msg, strlen(msg));
    lua_writeline();
    lua_pop(L, 1);  /* remove message */
  }
  return status;
}

int dostring (lua_State *L, const char *s, const char *name)
{
  int status = luaL_loadbuffer(L, s, strlen(s), name);

  if (status == LUA_OK)
  {
      status = lua_pcall(L, 0, 0, 0);
  }
  return report(L, status);
}


