/***********************************************************************/
/*                                                                     */
/*  FILE        :stacksct.h                                            */
/*  DESCRIPTION :Setting of Stack area                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator.               */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
#pragma stacksize su=0x200      
#pragma stacksize si=0x200      
